POST http://localhost:8080/auth/register HTTP/1.1
content-type: application/json

{
    "username": "testing3",
    "password": "wongwee"
}
###
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "testing3",
    "password": "wongwee"
}

###
GET http://localhost:8080/user HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmczIiwiaWF0IjoxNjc1NTA5ODAxLCJleHAiOjE2NzU1OTYyMDF9.QBTYHReO7_m-3HLZuOr4VAA5yxb6ddLvowyRTSlpbQM

###
GET http://localhost:8080/api/stat HTTP/1.1

### Update the count of the station
PUT http://localhost:8080/api/stat HTTP/1.1
content-type: application/json

{
    "id": 2,
    "count": 5
}

### Add the station
POST http://localhost:8080/api/stat HTTP/1.1
content-type: application/json

{
    "id": 3,
    "count": 6,
    "capacity": 10
}

### Use the station
POST http://localhost:8080/user/usestation HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmczIiwiaWF0IjoxNjc1NTQyNzU5LCJleHAiOjE2NzU2MjkxNTl9.b9k0xEkRx4C5pt7gctcm6UVUb5oD7WZheHe2TroEWtE

{
    "stationId": 1
}